### ISSUE TITLE
请问下目前是不支持保存磁力链接吗？

### ISSUE THREAD

**Issue by l987845225** [gsxhnd/garage#1]
#### 还有请问下怎么设置输出的文件夹，cmd里键入之后没有看到有文件输出下
```
C:\Users\Administrator\Desktop\xjwjj>garage crawl_code --proxy "http://127.0.0.1:10809" SDDE-603
2023-03-18T09:02:30.458764+00:00        [34mINFO[0m   Download info: SDDE-603
```

**Comment by gsxhnd** [comment]
1. 默认输出在当前目录
2. 磁力连接你想怎么保存，全部存在文件里吗？

**Comment by hanyaa-wut** [comment]
请问现在不能够通过演员ID索引吗，为什么我使用命令什么也没下载呀

**Comment by gsxhnd** [comment]
> 请问现在不能够通过演员ID索引吗，为什么我使用命令什么也没下载呀

番名前缀和演员ID 会在下一个版本支持这个功能

**Comment by gsxhnd** [comment]
> 请问现在不能够通过演员ID索引吗，为什么我使用命令什么也没下载呀

前缀功能已经实现

**Comment by aiastia** [comment]
> * 默认输出在当前目录，在 `v0.0.7`版本修复 已经修复 [fix: dir not create #2](https://github.com/gsxhnd/garage/pull/2)  [v0.0.7](https://github.com/gsxhnd/garage/releases/tag/v0.0.7)
> * 磁力连接你想怎么保存，全部存在文件里吗？

保存在 txt里面 然后批量导入115

**Comment by gsxhnd** [comment]
> > * 默认输出在当前目录，在 `v0.0.7`版本修复 已经修复 [fix: dir not create #2](https://github.com/gsxhnd/garage/pull/2)  [v0.0.7](https://github.com/gsxhnd/garage/releases/tag/v0.0.7)
> > * 磁力连接你想怎么保存，全部存在文件里吗？
> 
> 保存在 txt里面 然后批量导入115

一个页面下有多个磁力连接，默认会全部下载

**Comment by gsxhnd** [comment]
https://github.com/gsxhnd/garage/blob/d13ec9e3ddf20fa99da692df0f23e24cd9704c31/src/crawl/javbus.go#LL49C37-L49C37

**Comment by aiastia** [comment]
> > > * 默认输出在当前目录，在 `v0.0.7`版本修复 已经修复 [fix: dir not create #2](https://github.com/gsxhnd/garage/pull/2)  [v0.0.7](https://github.com/gsxhnd/garage/releases/tag/v0.0.7)
> > > * 磁力连接你想怎么保存，全部存在文件里吗？
> > 
> > 
> > 保存在 txt里面 然后批量导入115
> 
> 一个页面下有多个磁力连接，默认全部下载？

设置一个选项 下载 最大的 或者全部下载……

**Comment by aiastia** [comment]
https://github.com/qiqiandfei/JavSpider#:~:text=4%E3%80%81%E6%98%AF%E5%90%A6%E6%8A%93%E5%8F%96%E5%85%A8%E9%83%A8%E7%A3%81%E5%8A%9B%EF%BC%9A,%E5%8F%AA%E6%8A%93%E5%8F%96%E5%AE%A1%E6%A0%B8%E9%80%9A%E8%BF%87%E7%9A%84%E7%A3%81%E5%8A%9B

**Comment by aiastia** [comment]
这个好久没更新了 之前用的这个

**Comment by gsxhnd** [comment]
磁力列表获取成功，接下来就是添加到处功能

https://github.com/gsxhnd/garage/blob/1b7f89e71d968a09ab435891372bc20ce663c34c/src/crawl/javbus.go#L54-L123

**Comment by aiastia** [comment]
> 爬取需要添加header爬虫框架有点问题，需要使用额外的http client 才能获取

👍期待

**Comment by gsxhnd** [comment]
磁力链接下载 #5  [v0.0.8](https://github.com/gsxhnd/garage/releases/tag/v0.0.8)

**Comment by aiastia** [comment]
> 1. 磁力链接下载 [Feature/jav magnet #5](https://github.com/gsxhnd/garage/pull/5)
> 2. 新的版本已经发布 [v0.0.8](https://github.com/gsxhnd/garage/releases/tag/v0.0.8)

./g* crawl jav-prefix-code --magnet SDDE 

win 好像不能获取磁力， 文件是空的

**Comment by gsxhnd** [comment]
```text
   --proxy value        代理配置,如: http://127.0.0.1:1080
   --site value         选择爬取数据的网站,支持网站(javbus) (default: "javbus")
   --output value       设置下载目录 (default: "./javbus")
   --magnet             保存磁力链接,开启参数 --magnet (default: false)
   --prefix-code value  番号前缀 (default: "EKDV")
   --prefix-min value   番号开始编号 (default: 1)
   --prefix-max value   番号结束编号 (default: 5)
   --help, -h           show help
```

prefix-code 不填写默认使用的是 EKDV
./g* crawl jav-prefix-code --magnet  --prefix-code=SDDE --prefix-min=100 --prefix-max=110

**Comment by gsxhnd** [comment]
> jav-star-code jav-code-from-dir 这两个好像不支持 magnet 参数
jav-code-from-dir 是根据本地的视频爬取信息，视频本身已经存在了就不需要下载磁力链接。
jav-star-code 还没实现，我应该没有加到命令行中吧？

**Comment by aiastia** [comment]
> jav-star-code

jav-star-code  有望加上吗？

jav-code-from-dir 感觉加上也行 比如分享的时候

**Comment by gsxhnd** [comment]
> > jav-star-code
> 
> jav-star-code 有望加上吗？
> 
> jav-code-from-dir 感觉加上也行 比如分享的时候

jav-star-code 后续会实现 #6 
jav-code-from-dir 的magnet 到时候下个版本一起加上

**Comment by ND-LJQ** [comment]
这个如何运行呢,需要什么环境呢,我直接使用win的版本,闪退

**Comment by gsxhnd** [comment]
> 这个如何运行呢,需要什么环境呢,我直接使用win的版本,闪退

二进制由github action 自动编译上传。 直接下载release中windows对应的版本就行

**Comment by ikuntrue199** [comment]
> 尝试添加爬取磁力链接的代码，但似乎有反爬机制，需要获取gid uc img 作为ajax的query请求
> 
> ```
> <script>
> 	var gid = 54556884068;
> 	var uc = 0;
> 	var img = '/pics/cover/9q3z_b.jpg';
> </script>
> ```
> 
> ```
> $(function() {
>     var t = "../ajax/uncledatoolsbyajax.php?gid=" + gid + "&lang=" + lang + "&img=" + img + "&uc=" + uc + "&floor=" + Math.floor(1e3 * Math.random() + 1);
>     $.ajax({
>         url: t,
>         type: "GET",
>         success: function(t) {
>             $("#magnet-table").append(t)
>         }
>     })
> });
> ```
> 
> 尽管能获取到这些参数并处理成url还是无法请求到磁力链接列表
> 
> https://github.com/gsxhnd/garage/blob/d13ec9e3ddf20fa99da692df0f23e24cd9704c31/src/crawl/javbus.go#L49-L81

最近在看爬虫项目，不过我一般是用python玩，想请问一下这部分是如何获取到gid uc img 等数据的呢

**Comment by gsxhnd** [comment]
@ikuntrue199 正常获取

https://github.com/gsxhnd/garage/blob/f6052ebad81caf3df9cc019571fdc07b7549e06b/src/crawl/javbus.go#L190-L201
