### ISSUE TITLE
所有连接都是无磁力了

### ISSUE THREAD

**Issue by aiastia** [gsxhnd/garage#11]
应该是api 有变动

**Comment by gsxhnd** [comment]
试了下，网页确实有变动，获取不到正确的gid

**Comment by gsxhnd** [comment]
未登陆javbus情况下，访问页面会重定向到登录页面，导致爬取失败。
暂时不确定是特定IP还是所有IP都需要

**Comment by gsxhnd** [comment]
当前通过不执行302状态的跳转获取并分析返回数据，不知道能支持多久
