### ISSUE TITLE
jav-star-code crawl subcommand

### ISSUE THREAD

**Issue by gsxhnd** [gsxhnd/garage#6]

**Comment by ND-LJQ** [comment]
![image](https://github.com/gsxhnd/garage/assets/77595446/fa60cb51-6bc4-4b8f-b2d6-81d6d177297a)

centos7环境中使用命令后输出文件中内容为空

**Comment by gsxhnd** [comment]
虚拟机吃不到宿主机的代理，如有宿主机的代理可以允许局域网访问 添加proxy 选项，指向宿主机代理端口

**Comment by ND-LJQ** [comment]
但是我使用windows打开exe直接闪退

**Comment by gsxhnd** [comment]
在终端中运行， 没有gui

**Comment by ND-LJQ** [comment]
ok,懂了,谢谢大佬

**Comment by aiastia** [comment]
./g* crawl jav-star-code  视乎无法爬取。

**Comment by aiastia** [comment]
var javStarCodeCmd = &cli.Command{
Name: "jav-star-code",
Usage: "根据演员ID爬取数据",
Flags: []cli.Flag{
javSiteFlag,
javOutputFlag,
javProxyFlag,
},
Action: func(c *cli.Context) error {
return nil
},
}

**Comment by gsxhnd** [comment]
> ./g* crawl jav-star-code 视乎无法爬取。

这部分功能还没实现，暂时只预留了命令行

**Comment by gsxhnd** [comment]
relaese v0.0.9 beta 1 @aiastia @ND-LJQ

**Comment by ND-LJQ** [comment]
大佬有研究过加上javdb网站爬取吗

**Comment by gsxhnd** [comment]
> 大佬有研究过加上javdb网站爬取吗


网站对应番号的地址不知道是怎么生成的。后面有需求再说

**Comment by aiastia** [comment]
> relaese v0.0.9 beta 1 @aiastia @ND-LJQ

 ./g* crawl jav-star-code --magnet  --star-code z9z

--magnet 这个好像不会下载磁力
